ph.homecredit.weatherlog.api:
  weatherMapAPIURI: https://api.openweathermap.org/data/2.5
  weatherMapAPIKey: xxx-insert-api-key-here-xxx

server:
  port: 8081

logging.level:
    org.springframework.data: DEBUG
    ph.homecredit.weatherlog.api: DEBUG